name: test-dependencies

on:
  pull_request:
    branches:
      - main

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: 3.8

      - name: Install requirements
        working-directory: ./hexo_circle_of_friends
        run: |
          pip install -r requirements.txt
